## Object oriented programming

In [ ]:
class ClassName:
    #some functions and variables
    #function - used to perform a specific activity
    #variables - Data(memory)

In [ ]:
def test():
    return

In [5]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()


test() for the class and method


In [14]:
#Factorial of a number
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(5)) #120

120


In [ ]:
#Method
#def test(self,para1,para2):

In [16]:
class demo2:
    def Accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(self):
        print("p1=",p1)
        print("p2=",p2)
c1=Demo2()
c1.accept(10,20)
c1.display()



NameError: name 'Demo2' is not defined

In [19]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))


300


In [27]:
#self inheritance
#parent class
class Person():
    #constructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
#Derived Class
class Employee(Person):
    def isEmployee(self):
        return True
emp=Person("Anou")
print(emp.getName(),emp.isEmployee())

emp1=Employee("Merg")
print(emp1.getName(),emp1.isEmployee())

    

Anou False
Merg True


### Python Numpy

##### NumPy array is a central data structure  of the numpy lib. This lib is actually short for "Numeris Python" or "Numerical Python"

In [28]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [5]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [3]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [10]:
#Re-shape the given array
#numpy.reshape(arrayName,reshape,order='C')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
print(a1.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [11]:
#Append data--Horizontally
#hstack(array1,array2)--will be automatically arranged in horizontally 

a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [12]:
#Append some data--Vertical
#vstack(array1,array2)--will be automatically arranged in vertical
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [13]:
#Generate random numbers from NP
a1=np.random.normal(5,0.5,10)
print(a1)

[4.94260557 5.65723297 5.13699787 5.87855275 5.09678537 4.21248645
 5.81654599 5.20227871 5.03948541 4.83064742]


In [17]:
#numpy.zeros() and numpy.one()
#generate an array with all zeroes--numpy.zeros()
#numpy.zeros(shape,dtype=float,order='C')
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
print(np.zeros((2,2),dtype=np.int64))

[[0 0]
 [0 0]]


In [21]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [23]:
#np.ones(shape,dtype=float,order='C')
print(np.ones((4,3),dtype=np.int64))

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [27]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [4]:
#arrange()--particular
#numpy,arrange(start,end,stop)
#start-value
#end-value
#step-Gap between one value to another value
import numpy as np
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [6]:
# Indexing and Slicing of Numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Row:",a1[0])

First Row: [1 2 3]


In [8]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Row:",a1[1])

First Row: [4 5 6]


In [9]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[5.0475078  5.20568535 4.00391452 5.76874544 4.88611737 5.45773649
 5.92794899 3.76951564 6.11073982 7.55348482]
Min value= 3.7695156392930227
Max value= 7.5534848169089255
Mean value= 5.373139623208356
Median value= 5.331710919769357


In [11]:
# Multiply of 1D arrays
# numpy.dot(x,y) --

c1=np.array([1,2])
c2=np.array([4,5])
print(np.dot(c1,c2))


14


In [16]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
print(np.dot(c1,c2))
print(np.matmul(c1,c2))

[[ 5  8]
 [13 20]]
[[ 5  8]
 [13 20]]


In [17]:
class Foo:
    def printLine(self,line="Python"):
        print(line)
        
o1=Foo()
o1.printLine("Java")


Java


In [18]:
import numpy as np
a=np.array([1,2,3,5,8])
b=np.array([0,3,4,2,1])
c=a+b
c=c*a

print(c[2])

21


In [3]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com"],"MobileNumber":[999,888,777,888,777],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd


In [7]:
import calendar
a=calendar.prcal(2019)

                                  2019

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                   1  2  3
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       4  5  6  7  8  9 10
14 15 16 17 18 19 20      11 12 13 14 15 16 17      11 12 13 14 15 16 17
21 22 23 24 25 26 27      18 19 20 21 22 23 24      18 19 20 21 22 23 24
28 29 30 31               25 26 27 28               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     

In [13]:
def frequency(a):
    i=0
    while(i<=9):
        count=0
        for j in range(len(a)):
            if(ord(a[j])>=48 and ord(a[j])<=56):
                if i==int(a[j]):
                    count=count+1
        print(count,end=" ")
        i=i+1
a="213abc456def111"
frequency(a)

0 4 1 1 1 1 1 0 0 0 

In [14]:
def check(s1,s2):
    # the sorted strings are checked
    if(sorted(s1)==sorted(s2)):
        print("the strings are anagrams.")
    else:
        print("The strings aren't anagrams.")
        
#driver code
s1="listen"
s2="silent"
check(s1,s2)

the strings are anagrams.
